# setting up a MySQL database container.
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-data:

# find if ports are free
# netstat -aon | findstr :3306
# netstat -aon | findstr :8080

# docker-compose up -d
# http://localhost:8080
# Server: mysql
# Username: admin
# Password: admin
# Database: admin
